export const cards = [
  {
    w: "get sucked into",
    m: "不知不觉陷入；被卷入",
    e: "It's easy to get sucked into scrolling through social media.",
  },
  {
    w: "get a sense of where you're at",
    m: "了解自己目前处于什么状态或水平",
    e: "I took a mock test to get a sense of where I'm at.",
  },
  {
    w: "chip away at",
    m: "一点一点地减少、解决或完成",
    e: "I've been slowly chipping away at my student-loan debt.",
  },
  {
    w: "out of the blue",
    m: "突然地；出乎意料地",
    e: "I received a job offer completely out of the blue.",
  },
  {
    w: "account for",
    m: "考虑到；把……纳入考虑",
    e: "We need to account for inflation when comparing prices over time.",
  },
  {
    w: "set yourself up for success",
    m: "为成功做好准备",
    e: "Building good habits now will set you up for success later.",
  },
  {
    w: "take advantage of",
    m: "充分利用",
    e: "I want to take advantage of the next two months to improve my spoken English.",
  },
  {
    w: "pile up",
    m: "不断积累；越堆越多",
    e: "My assignments started to pile up toward the end of the semester.",
  },
  {
    w: "have money left over",
    m: "还剩下钱",
    e: "After paying my bills, I didn't have much money left over.",
  },
  {
    w: "boost your income",
    m: "增加收入",
    e: "A part-time job can help boost your income.",
  },
  {
    w: "give a window into sth.",
    m: "让人了解……；提供观察……的窗口",
    e: "The survey gives us a window into how young people think about work.",
  },
]

export const financeCards = [
  [
    "cash flow",
    "现金流",
    "Keeping track of your cash flow can help you understand where your money is going.",
  ],
  [
    "money coming in / money going out",
    "资金流入 / 资金流出",
    "I started tracking the money coming in and going out every month.",
  ],
  [
    "income",
    "收入",
    "My goal this year is to develop an additional source of income.",
  ],
  [
    "expenses",
    "支出；开支",
    "Rent accounts for a large proportion of my monthly expenses.",
  ],
  [
    "month-to-month expenses",
    "每月固定或经常发生的日常开支",
    "I reviewed my month-to-month expenses and realized I was spending too much on subscriptions.",
  ],
  [
    "balance sheet",
    "资产负债表",
    "Creating a personal balance sheet gives you a clearer picture of your financial situation.",
  ],
  [
    "assets",
    "资产",
    "Her assets include savings, stocks and a small apartment.",
  ],
  [
    "debt",
    "债务",
    "He is trying to pay off his credit-card debt as quickly as possible.",
  ],
  [
    "mortgage",
    "住房抵押贷款；房贷",
    "They took out a mortgage to buy their first home.",
  ],
  [
    "emergency fund / emergency reserve fund",
    "应急资金；应急储备金",
    "Financial experts often recommend building an emergency fund to cover unexpected expenses.",
  ],
  [
    "cash on hand",
    "手头可立即使用的现金或资金",
    "It’s a good idea to keep some cash on hand for emergencies.",
  ],
  [
    "investment",
    "投资",
    "Diversifying your investments can help reduce financial risk.",
  ],
  [
    "net income",
    "净收入",
    "Her net income increased after she switched to a higher-paying job.",
  ],
  [
    "deductions",
    "扣除额；扣款",
    "After taxes and other deductions, his take-home pay is about $4,000 a month.",
  ],
  [
    "the bottom line",
    "净利润；最终财务结果；归根结底",
    "The company’s bottom line improved significantly this year.",
  ],
  [
    "money left over",
    "剩余资金；剩下的钱",
    "After paying rent, bills and other expenses, I usually have about $500 left over.",
  ],
  [
    "savings",
    "储蓄；存款",
    "I'm trying to put at least 20% of my monthly income into savings.",
  ],
  [
    "quarterly report",
    "季度报告",
    "The company reported stronger-than-expected earnings in its latest quarterly report.",
  ],
]

export const quizzes = [
  {
    q: "“不知不觉陷入刷社交媒体”最自然的表达是？",
    opts: ["get sucked into", "chip away at", "out of the blue", "account for"],
    a: 0,
    en: "It's easy to **get sucked into** scrolling through social media.",
    zh: "人很容易不知不觉一直刷社交媒体。",
    key: "get sucked into",
  },
  {
    q: "“一点一点地偿还债务”可以说？",
    opts: [
      "pile up your debt",
      "chip away at your debt",
      "boost your debt",
      "get sucked into debt",
    ],
    a: 1,
    en: "I've been slowly **chipping away at** my student-loan debt.",
    zh: "我一直在一点一点偿还学生贷款。",
    key: "chip away at",
  },
  {
    q: "“了解自己目前的水平”可以说？",
    opts: [
      "get a sense of where you’re at",
      "set yourself up for",
      "take advantage of",
      "give a window into",
    ],
    a: 0,
    en: "I took a mock test to **get a sense of where I'm at**.",
    zh: "我做了一次模拟考试，想了解一下自己目前的水平。",
    key: "get a sense of where you're at",
  },
  {
    q: "“突然收到一份工作邀请”里的“突然”是？",
    opts: ["month to month", "left over", "out of the blue", "on hand"],
    a: 2,
    en: "I received a job offer completely **out of the blue**.",
    zh: "我突然收到了一份工作邀请。",
    key: "out of the blue",
  },
  {
    q: "“考虑通货膨胀”可以说 account ___ inflation。",
    opts: ["into", "for", "over", "up"],
    a: 1,
    en: "We need to **account for** inflation when comparing prices over time.",
    zh: "比较不同时期的价格时，我们需要考虑通货膨胀。",
    key: "account for",
  },
  {
    q: "“为未来的成功做好准备”可以说？",
    opts: [
      "set yourself up for success",
      "get sucked into success",
      "success piles up",
      "account for success",
    ],
    a: 0,
    en: "Building good habits now will **set you up for success** later.",
    zh: "现在养成良好的习惯会为未来的成功打下基础。",
    key: "set yourself up for success",
  },
  {
    q: "“调查让我们了解年轻人的想法”中的“让我们了解”是？",
    opts: [
      "give a window into",
      "have money left over",
      "boost your income",
      "out of the blue",
    ],
    a: 0,
    en: "The survey **gives us a window into** how young people think about work.",
    zh: "这项调查让我们了解到年轻人如何看待工作。",
    key: "gives us a window into",
  },
  {
    q: "“充分利用接下来的两个月”可以说？",
    opts: [
      "pile up the next two months",
      "take advantage of the next two months",
      "account for the next two months",
      "get sucked into the next two months",
    ],
    a: 1,
    en: "I want to **take advantage of** the next two months to improve my spoken English.",
    zh: "我想充分利用接下来两个月提高英语口语。",
    key: "take advantage of",
  },
  {
    q: "“我的作业开始越积越多”中的“越积越多”是？",
    opts: ["chip away at", "pile up", "out of the blue", "set yourself up for"],
    a: 1,
    en: "My assignments started to **pile up** toward the end of the semester.",
    zh: "临近期末，我的作业开始越积越多。",
    key: "pile up",
  },
  {
    q: "“付完账单后没剩多少钱”中的“没剩下”可以说？",
    opts: [
      "didn’t boost",
      "didn’t account for",
      "didn’t have much money left over",
      "didn’t pile up",
    ],
    a: 2,
    en: "After paying all my bills, I **didn't have much money left over**.",
    zh: "支付完所有账单后，我没剩多少钱。",
    key: "didn't have much money left over",
  },
  {
    q: "“兼职可以增加收入”中的“增加”是？",
    opts: [
      "boost your income",
      "account for your income",
      "pile up your income",
      "get sucked into your income",
    ],
    a: 0,
    en: "Taking a part-time job is one way to **boost your income**.",
    zh: "做兼职是增加收入的一种方式。",
    key: "boost your income",
  },
]

export const financeQs = [
  {
    before: "Keeping track of your ",
    after: " can help you understand where your money is going.",
    ans: "cash flow",
    opts: ["cash flow", "balance sheet", "emergency fund", "quarterly report"],
    hint: "一段时间内资金流入与流出。",
    zh: "记录现金流可以帮助你了解钱都花到哪里去了。",
  },
  {
    before: "I started tracking the ",
    after: " every month.",
    ans: "money coming in and going out",
    opts: [
      "money coming in and going out",
      "balance sheet",
      "net income",
      "quarterly report",
    ],
    hint: "用更口语的方式说每月资金流入和流出。",
    zh: "我开始每个月记录资金的流入和流出。",
  },
  {
    before: "My goal this year is to develop an additional source of ",
    after: ".",
    ans: "income",
    opts: ["income", "debt", "expense", "deduction"],
    hint: "收入；也常与 source of 搭配。",
    zh: "我今年的目标是增加一个额外的收入来源。",
  },
  {
    before: "Rent accounts for a large proportion of my monthly ",
    after: ".",
    ans: "expenses",
    opts: ["assets", "expenses", "savings", "investments"],
    hint: "个人日常支出；常用复数。",
    zh: "房租占我每月开支的很大一部分。",
  },
  {
    before: "I reviewed my ",
    after: " and noticed I was spending too much on subscriptions.",
    ans: "month-to-month expenses",
    opts: [
      "month-to-month expenses",
      "quarterly reports",
      "liquid assets",
      "cash on hand",
    ],
    hint: "每月固定或经常发生的日常开支。",
    zh: "我检查了每月日常开支，发现自己在订阅服务上花了太多钱。",
  },
  {
    before: "Creating a personal ",
    after: " gives you a clearer picture of your financial situation.",
    ans: "balance sheet",
    opts: [
      "balance sheet",
      "cash flow",
      "emergency fund",
      "investment portfolio",
    ],
    hint: "列出资产和负债，了解财务状况的报表。",
    zh: "制作个人资产负债表可以让你更清楚地了解自己的财务状况。",
  },
  {
    before: "Her ",
    after: " include savings, stocks and a small apartment.",
    ans: "assets",
    opts: ["deductions", "expenses", "assets", "debts"],
    hint: "你拥有的、具有经济价值的东西。",
    zh: "她的资产包括存款、股票以及一套小公寓。",
  },
  {
    before: "He is trying to pay off his credit-card ",
    after: " as quickly as possible.",
    ans: "debt",
    opts: ["debt", "income", "savings", "mortgage"],
    hint: "欠款；常见搭配 pay off。",
    zh: "他正在努力尽快还清信用卡债务。",
  },
  {
    before: "They took out a ",
    after: " to buy their first home.",
    ans: "mortgage",
    opts: ["mortgage", "quarterly report", "deduction", "cash flow"],
    hint: "购买住房时办理的贷款。",
    zh: "他们通过办理房贷购买了第一套住房。",
  },
  {
    before: "Building an ",
    after: " can help cover unexpected expenses.",
    ans: "emergency fund",
    opts: [
      "investment portfolio",
      "emergency fund",
      "balance sheet",
      "quarterly report",
    ],
    hint: "应对意外开支的储备金。",
    zh: "建立应急基金有助于应付意外开支。",
  },
  {
    before: "It’s a good idea to keep some ",
    after: " for emergencies.",
    ans: "cash on hand",
    opts: ["cash on hand", "net income", "monthly expenses", "investment"],
    hint: "手头可以立即使用的现金或资金。",
    zh: "留一些随时可以使用的现金应对紧急情况是个好主意。",
  },
  {
    before: "Diversifying your ",
    after: " can help reduce financial risk.",
    ans: "investments",
    opts: ["deductions", "investments", "expenses", "debts"],
    hint: "投资的复数形式；分散它们有助于分散风险。",
    zh: "分散投资有助于降低财务风险。",
  },
  {
    before: "Her ",
    after: " increased after she switched to a higher-paying job.",
    ans: "net income",
    opts: ["gross income", "net income", "cash on hand", "monthly expenses"],
    hint: "扣除相关费用后实际剩下的收入。",
    zh: "她换了一份薪资更高的工作后，净收入增加了。",
  },
  {
    before: "After taxes and other ",
    after: ", his take-home pay is about $4,000 a month.",
    ans: "deductions",
    opts: ["assets", "deductions", "savings", "expenses"],
    hint: "从工资或收入中扣除的款项。 take-home pay = 到手工资。",
    zh: "扣除税款和其他款项后，他每个月实际到手约4000美元。",
  },
  {
    before: "The company’s ",
    after: " improved significantly this year.",
    ans: "bottom line",
    opts: ["cash flow", "bottom line", "take-home pay", "assets"],
    hint: "财经语境下指最终盈利或财务结果。",
    zh: "公司的盈利状况今年显著改善。",
  },
  {
    before: "After paying rent, bills and other expenses, I have about $500 ",
    after: ".",
    ans: "left over",
    opts: ["left over", "coming in", "going out", "on hand"],
    hint: "支付完之后剩下的。",
    zh: "支付房租、账单和其他开支后，我通常还能剩下大约500美元。",
  },
  {
    before: "I’m trying to put at least 20% of my monthly income into ",
    after: ".",
    ans: "savings",
    opts: ["debt", "savings", "expenses", "deductions"],
    hint: "储蓄；也可表示存款。",
    zh: "我尽量把每月收入的至少20%存起来。",
  },
  {
    before:
      "The company reported stronger-than-expected earnings in its latest ",
    after: ".",
    ans: "quarterly report",
    opts: [
      "balance sheet",
      "quarterly report",
      "emergency fund",
      "cash on hand",
    ],
    hint: "公司每三个月发布一次的报告。",
    zh: "该公司在最新季度报告中公布的盈利好于预期。",
  },
]

export const prompts = [
  {
    topic: "The little things that add up",
    cn: "想想最近有什么事情越积越多，或你正在逐步处理的目标。",
    words: ["pile up", "chip away at"],
    tip: "回答之后再补充：什么时候开始？你怎么安排？有什么具体进展？",
    follow:
      "What is piling up? When did it start? What small step did you take this week?",
    ex: "My emails started to pile up, so I’m chipping away at them every morning.",
    zh: "我的邮件开始越积越多，所以我每天早上都在一点点处理。",
  },
  {
    topic: "A surprise opportunity",
    cn: "回忆一次意料之外的好消息、机会或变化。",
    words: ["out of the blue", "take advantage of"],
    tip: "再加上：当时你在哪里？为什么这个机会重要？接下来发生了什么？",
    follow:
      "When did it happen? Why did the opportunity matter to you? What did you do next?",
    ex: "A chance to study abroad came up out of the blue, and I decided to take advantage of it.",
    zh: "一个出国学习的机会突然出现，我决定好好把握。",
  },
  {
    topic: "A goal you’re working toward",
    cn: "说说你正在努力达成的目标，以及你如何为成功做准备。",
    words: ["get a sense of where you’re at", "set yourself up for success"],
    tip: "继续拓展：你如何衡量进度？每天做什么？遇到什么困难？",
    follow:
      "How do you measure your progress? What do you do regularly? What challenge have you faced?",
    ex: "I track my study hours to get a sense of where I’m at and set myself up for success.",
    zh: "我记录学习时长来了解自己的进度，并为成功做好准备。",
  },
]

export default {
  id: "2026-10-01-money",
  day: 1,
  date: "2026-10-01",
  title: "There’s still time to reach your 2026 money goals",
  tag: "个人财务 · MONEY",
  source: "NPR · Life Kit",
  sourceCode: "NPR",
  sourceUrl: "https://www.npr.org/2026/10/01/nx-s1-5986354/theres-still-time-to-reach-your-2026-money-goals",
  audioUrl: "https://tracking.swap.fm/track/XvDEoI11TR00olTUO8US/prfx.byspotify.com/e/play.podtrac.com/npr-510338/npr.simplecastaudio.com/8ae5a040-e346-4b89-ba6b-625f91f1fbd4/episodes/f211ba75-8972-426a-a27a-577509d04a6f/audio/128/default.mp3?awCollectionId=8ae5a040-e346-4b89-ba6b-625f91f1fbd4&awEpisodeId=f211ba75-8972-426a-a27a-577509d04a6f&feed=XkY2SBZJ&t=podcast&e=nx-s1-5986354&p=510338&d=1152&size=18440403",
  kind: "podcast",
  durationMinutes: 12,
  vocabularyLabel: "主题词汇",
  cards,
  financeCards,
  quizzes,
  financeQs,
  prompts,
} satisfies import("../types").Lesson
